app/urls.py
from django.urls import path
from . import views
app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_reminder', views.add_reminder, name='add_reminder'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/updating/', views.updating, name='updating'),
    path('<int:id>/delete', views.delete, name='delete'),
]

reminder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
]

app/models.py
from django.db import models

# Create your models here.
class Reminder(models.Model):
    note = models.CharField(max_length=100)
    date = models.DateField()

app/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponse

# Create your views here.


def index(request):
    reminder = Reminder.objects.all()
    return render(request, 'index.html', {'reminder': reminder})


def add_reminder(request):
    if request.method == 'POST':
        note = request.POST.get('note')
        date = request.POST.get('date')
        obj = Reminder()
        obj.note = note
        obj.date = date
        obj.save()
    reminder = Reminder.objects.all()
    return render(request, 'index.html', {'reminder': reminder})


def update(request, id):
    rem = Reminder.objects.get(pk=id)
    return render(request, 'update.html', {'rem': rem})


def updating(request, id):
    if request.method == 'POST':
        note = request.POST.get('note')
        date = request.POST.get('date')
        Reminder.objects.filter(pk=id).update(note=note, date=date)
    reminder = Reminder.objects.all()
    return render(request, 'index.html', {'reminder': reminder})


def delete(request, id):
    Reminder.objects.filter(pk=id).delete()
    reminder = Reminder.objects.all()
    return render(request, 'index.html', {'reminder': reminder})

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div align="center">
    <h1>REMINDERS</h1>
    <hr>
    <table>
        <tr>
            <th>No</th>
            <th></th>
            <th>Reminder</th>
            <th></th>
            <th>Date</th>
            <th></th>
        </tr>
        <tr>
                    {% for i in reminder %}
            <td>{{ forloop.counter }}</td>
            <td></td>
            <td>{{ i.note }}</td>
            <td></td>
            <td>{{ i.date }}</td>
                        <td></td>
            <td><a href="{% url 'app:update' i.id %}"><input type="submit" value="UPDATE"></a></td>
            <td><a href="{% url 'app:delete' i.id %}"><input type="submit" value="DELETE"></a></td>
        </tr>
        {% endfor %}
    </table>
</div>
<hr>
<div align="center">
     <form action="{% url 'app:add_reminder' %}" method="post">
        {% csrf_token %}
        <h1>ADD REMINDER</h1>
        <hr>
        <input type="text" placeholder="Note" required name="note">
        <input type="date" required name="date" >
        <input type="submit" value="Add Reminder">
         </form>
</div>
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'app:updating' rem.id %}" method="post">
    {% csrf_token %}
    <div align="center">
            <h1>UPDATE REMINDER</h1>
            <hr>
        <input type="text" placeholder="Note"  value="{{ rem.note }}" name="note" required>
        <input type="date" value="{{rem.date|date:"Y-m-d" }}" name="date" required>
        <input type="submit" value="UPDATE">
    </div>
</form>

</body>
</html>